export const Constants = 
{
    GETAPI_PRODUCTS : "GETAPI_PRODUCTS",
    GETAPI_PRODUCTS_SINGLE :"GETAPI_PRODUCTS_SINGLE",
    EDITAPI_PRODUCTS : "EDIT_API_PRODUCTS",
    POSTAPI_PRODUCTS : "POSTAPI_PRODUCTS",
    DELETEAPI_PRODUCTS :"DELETEAPI_PRODUCTS"
    
};